version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - NODE_TYPE=namenode
    ports:
      - "9870:9870"
      - "8088:8088"
      - "9000:9000"
    volumes:
      - namenode:/hadoop/dfs/name
    mem_limit: 2g
    networks:
      - hadoop-net
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - NODE_TYPE=datanode
    volumes:
      - datanode1:/hadoop/dfs/data
    mem_limit: 2g
    depends_on:
      - namenode
    networks:
      - hadoop-net
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - NODE_TYPE=datanode
    volumes:
      - datanode2:/hadoop/dfs/data
    mem_limit: 2g
    depends_on:
      - namenode
    networks:
      - hadoop-net
    env_file:
      - ./hadoop.env

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    hostname: datanode3
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - NODE_TYPE=datanode
    volumes:
      - datanode3:/hadoop/dfs/data
    mem_limit: 2g
    depends_on:
      - namenode
    networks:
      - hadoop-net
    env_file:
      - ./hadoop.env

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - PYSPARK_PYTHON=/usr/bin/python3
    env_file:
      - ./hadoop.env
    mem_limit: 1g
    networks:
      - hadoop-net


  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    env_file:
      - ./hadoop.env
    mem_limit: 1g
    networks:
      - hadoop-net


volumes:
  namenode:
  datanode1:
  datanode2:
  datanode3:

networks:
  hadoop-net:
    driver: bridge